//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UbitLibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_Details()
        {
            this.Borrower_Details = new HashSet<Borrower_Details>();
        }
    
        public int ISBN_Code { get; set; }
        public string Book_Title { get; set; }
        public string Book_Author { get; set; }
        public int Publication_id { get; set; }
        public int Category_id { get; set; }
        public int No_of_Copies_Actual { get; set; }
        public int No_of_Copies_Available { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrower_Details> Borrower_Details { get; set; }
        public virtual Category_Details Category_Details { get; set; }
        public virtual Publication_Details Publication_Details { get; set; }
    }
}
