//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UbitLibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrower_Details
    {
        public int PKBorrower_id { get; set; }
        public int Borrower_id { get; set; }
        public string Borrower_Name { get; set; }
        public int Book_id { get; set; }
        public System.DateTime Borrowed_From_Date { get; set; }
        public System.DateTime Borrowed_To_Date { get; set; }
        public int Issued_By { get; set; }
    
        public virtual Book_Details Book_Details { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
