//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UbitLibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Details
    {
        public int id { get; set; }
        public int Student_id { get; set; }
        public string Student_Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Program { get; set; }
        public string Contact_No { get; set; }
    }
}
